export const adminNav = [
  { label: "Ümumi baxış", href: "/admin", emoji: "🏠" },
  { label: "İstifadəçilər", href: "/admin/users", emoji: "👨‍👩‍👧" },
  { label: "Uşaqlar", href: "/admin/children", emoji: "🧒" },
  { label: "Abunəliklər", href: "/admin/subscriptions", emoji: "💳" },
  { label: "Kuponlar", href: "/admin/coupons", emoji: "🎟️" },
  { label: "Əyləncə yerləri", href: "/admin/entertainment", emoji: "🎡" },
  { label: "Yemək yerləri", href: "/admin/restaurants", emoji: "🍔" },
  { label: "Tədbirlər", href: "/admin/events", emoji: "📅" },
  { label: "Məzmun idarəsi", href: "/admin/content", emoji: "📋" },
  { label: "Bildirişlər", href: "/admin/notifications", emoji: "🔔" },
  { label: "Statistika", href: "/admin/statistics", emoji: "📊" },
  { label: "Tənzimləmələr", href: "/admin/settings", emoji: "⚙️" },
  { label: "Dəstək", href: "/admin/support", emoji: "❓" },
] as const;
